import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { campaignWorkspaceId } from "@/lib/campaign-workspace.storage";
import type { Campaign } from "@/lib/campaign-workspace.types";

const OBJECTIVES = ["品牌曝光", "销售转化", "App 下载", "注册留资", "私域增长", "产品教育", "市场测试"];
const TONES = ["专业", "科技感", "年轻化", "高端", "生活方式", "有趣", "理性", "情绪陪伴"];

function Field({ label, children }: { label: string; children: React.ReactNode }) {
  return <label className="block space-y-1"><span className="text-xs font-medium text-muted-foreground">{label}</span>{children}</label>;
}
function Select({ name, defaultValue, children }: { name: string; defaultValue?: string; children: React.ReactNode }) {
  return <select name={name} defaultValue={defaultValue} className="h-10 w-full rounded-md border border-input bg-background px-3 text-sm">{children}</select>;
}

export function CampaignFormDialog({ open, onOpenChange, campaign, onSave }: { open: boolean; onOpenChange: (open: boolean) => void; campaign?: Campaign | null; onSave: (campaign: Campaign) => void }) {
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[92vh] max-w-5xl overflow-y-auto"><DialogHeader><DialogTitle>{campaign ? "编辑投放项目" : "创建投放项目"}</DialogTitle><DialogDescription>填写品牌 Brief、预算、人群和投放限制，后续可在项目内添加候选播客。</DialogDescription></DialogHeader>
    <form key={campaign?.id ?? "new"} className="space-y-6" onSubmit={(event) => {event.preventDefault(); const form = new FormData(event.currentTarget); const now = new Date().toISOString(); const value = (name: string) => String(form.get(name) ?? "").trim(); onSave({id: campaign?.id ?? campaignWorkspaceId("campaign"), campaignName: value("campaignName"), brandName: value("brandName"), brandWebsite: value("brandWebsite") || undefined, productDescription: value("productDescription"), productCategory: value("productCategory") || undefined, targetMarket: value("targetMarket") as Campaign["targetMarket"], budget: Number(form.get("budget")) || 0, currency: value("currency") as Campaign["currency"], objective: value("objective"), targetAudience: value("targetAudience"), audienceAgeRange: value("audienceAgeRange") || undefined, audienceGender: value("audienceGender") || undefined, audienceLocation: value("audienceLocation") || undefined, audienceInterest: value("audienceInterest") || undefined, brandTone: value("brandTone"), preferredCategories: value("preferredCategories"), forbiddenTopics: value("forbiddenTopics") || undefined, blockedIndustries: value("blockedIndustries") || undefined, requiredMessage: value("requiredMessage") || undefined, campaignStartDate: value("campaignStartDate") || undefined, campaignEndDate: value("campaignEndDate") || undefined, status: value("status") as Campaign["status"], createdAt: campaign?.createdAt ?? now, updatedAt: now}); onOpenChange(false);}}>
      <section><h3 className="text-sm font-semibold">基础信息</h3><div className="mt-3 grid gap-3 md:grid-cols-2"><Field label="Campaign 名称 *"><Input name="campaignName" required defaultValue={campaign?.campaignName} /></Field><Field label="品牌名称 *"><Input name="brandName" required defaultValue={campaign?.brandName} /></Field><Field label="品牌官网"><Input name="brandWebsite" type="url" defaultValue={campaign?.brandWebsite} /></Field><Field label="产品类别"><Input name="productCategory" defaultValue={campaign?.productCategory} /></Field><div className="md:col-span-2"><Field label="产品描述 *"><Textarea name="productDescription" required rows={3} defaultValue={campaign?.productDescription} /></Field></div><Field label="目标市场"><Select name="targetMarket" defaultValue={campaign?.targetMarket ?? "china"}><option value="china">中国</option><option value="north_america">北美</option><option value="europe">欧洲</option><option value="global">全球</option><option value="other">其他</option></Select></Field><div className="grid grid-cols-[1fr_120px] gap-2"><Field label="预算 *"><Input name="budget" type="number" min="0" required defaultValue={campaign?.budget} /></Field><Field label="货币"><Select name="currency" defaultValue={campaign?.currency ?? "CNY"}><option>CNY</option><option>USD</option><option>EUR</option><option>GBP</option></Select></Field></div></div></section>
      <section><h3 className="text-sm font-semibold">目标人群</h3><div className="mt-3 grid gap-3 md:grid-cols-2"><Field label="投放目标"><Select name="objective" defaultValue={campaign?.objective ?? OBJECTIVES[0]}>{OBJECTIVES.map((item) => <option key={item}>{item}</option>)}</Select></Field><Field label="目标人群 *"><Input name="targetAudience" required defaultValue={campaign?.targetAudience} /></Field><Field label="年龄范围"><Input name="audienceAgeRange" defaultValue={campaign?.audienceAgeRange} /></Field><Field label="性别"><Input name="audienceGender" defaultValue={campaign?.audienceGender} /></Field><Field label="地域"><Input name="audienceLocation" defaultValue={campaign?.audienceLocation} /></Field><Field label="兴趣"><Input name="audienceInterest" defaultValue={campaign?.audienceInterest} /></Field></div></section>
      <section><h3 className="text-sm font-semibold">品牌偏好与排期</h3><div className="mt-3 grid gap-3 md:grid-cols-2"><Field label="品牌语气"><Select name="brandTone" defaultValue={campaign?.brandTone ?? TONES[0]}>{TONES.map((item) => <option key={item}>{item}</option>)}</Select></Field><Field label="偏好播客分类 *"><Input name="preferredCategories" required defaultValue={campaign?.preferredCategories} placeholder="如：科技、商业、生活方式" /></Field><Field label="禁投话题"><Input name="forbiddenTopics" defaultValue={campaign?.forbiddenTopics} /></Field><Field label="屏蔽行业"><Input name="blockedIndustries" defaultValue={campaign?.blockedIndustries} /></Field><div className="md:col-span-2"><Field label="必须传达的信息"><Textarea name="requiredMessage" rows={2} defaultValue={campaign?.requiredMessage} /></Field></div><Field label="开始日期"><Input name="campaignStartDate" type="date" defaultValue={campaign?.campaignStartDate} /></Field><Field label="结束日期"><Input name="campaignEndDate" type="date" defaultValue={campaign?.campaignEndDate} /></Field><Field label="状态"><Select name="status" defaultValue={campaign?.status ?? "draft"}><option value="draft">草稿</option><option value="planning">规划中</option><option value="contacting">建联中</option><option value="negotiating">谈判中</option><option value="confirmed">已确认</option><option value="live">已上线</option><option value="completed">已复盘</option><option value="paused">已暂停</option></Select></Field></div></section>
      <div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={() => onOpenChange(false)}>取消</Button><Button type="submit">{campaign ? "保存修改" : "创建投放项目"}</Button></div>
    </form></DialogContent></Dialog>;
}
