/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PodcastIdRouteImport } from './routes/podcast.$id'
import { Route as ApiPublicHooksStrategyRefreshRouteImport } from './routes/api/public/hooks/strategy-refresh'
import { Route as ApiPublicHooksDailyRefreshRouteImport } from './routes/api/public/hooks/daily-refresh'

const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PodcastIdRoute = PodcastIdRouteImport.update({
  id: '/podcast/$id',
  path: '/podcast/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksStrategyRefreshRoute =
  ApiPublicHooksStrategyRefreshRouteImport.update({
    id: '/api/public/hooks/strategy-refresh',
    path: '/api/public/hooks/strategy-refresh',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDailyRefreshRoute =
  ApiPublicHooksDailyRefreshRouteImport.update({
    id: '/api/public/hooks/daily-refresh',
    path: '/api/public/hooks/daily-refresh',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/planner': typeof PlannerRoute
  '/podcast/$id': typeof PodcastIdRoute
  '/api/public/hooks/daily-refresh': typeof ApiPublicHooksDailyRefreshRoute
  '/api/public/hooks/strategy-refresh': typeof ApiPublicHooksStrategyRefreshRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/planner': typeof PlannerRoute
  '/podcast/$id': typeof PodcastIdRoute
  '/api/public/hooks/daily-refresh': typeof ApiPublicHooksDailyRefreshRoute
  '/api/public/hooks/strategy-refresh': typeof ApiPublicHooksStrategyRefreshRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/planner': typeof PlannerRoute
  '/podcast/$id': typeof PodcastIdRoute
  '/api/public/hooks/daily-refresh': typeof ApiPublicHooksDailyRefreshRoute
  '/api/public/hooks/strategy-refresh': typeof ApiPublicHooksStrategyRefreshRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/planner'
    | '/podcast/$id'
    | '/api/public/hooks/daily-refresh'
    | '/api/public/hooks/strategy-refresh'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/planner'
    | '/podcast/$id'
    | '/api/public/hooks/daily-refresh'
    | '/api/public/hooks/strategy-refresh'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/planner'
    | '/podcast/$id'
    | '/api/public/hooks/daily-refresh'
    | '/api/public/hooks/strategy-refresh'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  PlannerRoute: typeof PlannerRoute
  PodcastIdRoute: typeof PodcastIdRoute
  ApiPublicHooksDailyRefreshRoute: typeof ApiPublicHooksDailyRefreshRoute
  ApiPublicHooksStrategyRefreshRoute: typeof ApiPublicHooksStrategyRefreshRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcast/$id': {
      id: '/podcast/$id'
      path: '/podcast/$id'
      fullPath: '/podcast/$id'
      preLoaderRoute: typeof PodcastIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/strategy-refresh': {
      id: '/api/public/hooks/strategy-refresh'
      path: '/api/public/hooks/strategy-refresh'
      fullPath: '/api/public/hooks/strategy-refresh'
      preLoaderRoute: typeof ApiPublicHooksStrategyRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/daily-refresh': {
      id: '/api/public/hooks/daily-refresh'
      path: '/api/public/hooks/daily-refresh'
      fullPath: '/api/public/hooks/daily-refresh'
      preLoaderRoute: typeof ApiPublicHooksDailyRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  PlannerRoute: PlannerRoute,
  PodcastIdRoute: PodcastIdRoute,
  ApiPublicHooksDailyRefreshRoute: ApiPublicHooksDailyRefreshRoute,
  ApiPublicHooksStrategyRefreshRoute: ApiPublicHooksStrategyRefreshRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
